"""Initial Migration

Revision ID: ba0eeceb32ab
Revises: e19cc7efa1ea
Create Date: 2021-06-16 10:38:48.028434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0eeceb32ab'
down_revision = 'e19cc7efa1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'pitches', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    # ### end Alembic commands ###
