"""Initial Migration

Revision ID: e19cc7efa1ea
Revises: 81c406c880f5
Create Date: 2021-06-16 10:24:26.180082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19cc7efa1ea'
down_revision = '81c406c880f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('votes')
    op.drop_constraint('pitches_category_fkey', 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'vote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pitches_category_fkey', 'pitches', 'categories', ['category'], ['id'])
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='votes_comment_id_fkey'),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], name='votes_pitch_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey')
    )
    op.drop_table('likes')
    op.drop_table('dislikes')
    # ### end Alembic commands ###
